### ISSUE TITLE
How do I login with Google?

### ISSUE THREAD

**Issue by wolph** [jason0x43/alfred-toggl#1]
I've just signed up with Toggl but I did it using the "Sign up with Google" button, I just don't see how I can login in this workflow :)

**Comment by colinharman** [comment]
I'm in the same boat. Not sure how you'd use the google auth to differentiate logins, but I think if anyone can figure it out, it's Jason.

**Comment by wolph** [comment]
For the time being I just did a reset password on toggl so I would have a normal login as well. But it's inconvenient to say the least ;)

**Comment by jason0x43** [comment]
There isn't a direct way to login to the Toggl API with non-Toggl credentials. The only option other than email + password is to use your account API token. For that, I could add an alternate login method that would accept an API token, which users would retrieve from their account settings.

**Comment by jason0x43** [comment]
[Release 1.1.0](https://github.com/jason0x43/alfred-toggl/releases/tag/v1.1.0) includes a new `token` command that will let you input your API token directly.

**Comment by wolph** [comment]
Awesome, thanks for the quick response
