### ISSUE TITLE
Starting a new task doesn't stop current task

### ISSUE THREAD

**Issue by jb510** [jason0x43/alfred-toggl#10]
Steps:

```
tgl timers new

tgl timers new2
```

and I see this:
https://cloudup.com/cY1mmXzloqT

Maybe things are just slow to update, but what I'd expect is for the existing timer to stop and then a new timer to start which is what actually happens on Toggl, just not inside Alfred

Then I tried

```
tgl timers new3
```

and looking at Toggl.com I see this:
https://cloudup.com/cTo4wle5m1c
which is very confusing
Occurs to me this is possibly related to #8.

**Comment by jason0x43** [comment]
This is a UI bug on my end. Toggl doesn't actually allow multiple timers to run at the same time.

**Comment by jason0x43** [comment]
Fixed in 4f1ef329927767d0a09d4da18ffa3380cc616640
