### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/alfred-toggl#11]
UI improvement time! The menu-based system works well enough, and things are nicely discoverable, but it's not particularly user friendly for everyday use. Instead, mimic the flow of the web interface.
- `tgl` should bring up a filterable list of timers.
- Actioning a timer will stop it (if running), or continue it (using the user's preferred continuation behavior). 
- Tabbing a timer will focus on it and allow timer options to be changed, and maybe provide some built in modifications (like rounding up or down).
- Use a separate keyword for starting commands ('tstart' or something)
- Figure out a decent way to specify projects when starting commands. The current system of navigating to a project and starting a command from it works, but is a bit kludgy

**Comment by rezzz-dev** [comment]
+1 on 

> Figure out a decent way to specify projects when starting commands. The current system of navigating to a project and starting a command from it works, but is a bit kludgy

It'd be nice to be able to tab upon the start of a new timer to go right down the line. So for example:
timer >> [new timer desc] >> project >> tags

**Comment by jason0x43** [comment]
The UI has been significantly improved (at least to me) in master. The original `tgl` menu exists, but most commands can now be directly accessed via keywords (e.g., `tgr` == `tgl report`).

Most sections of the UI are now handled as distinct modes. So, for example, you would type `tgr week` and press Enter to switch to a weekly report mode, or `tgl projects` followed by Enter to switch to the project list.

Projects can be specified when starting a time by pressing the Alt key when actioning it. I plan to add an option to make that the default flow.
