### ISSUE TITLE
Implement continue feature.

### ISSUE THREAD

**Issue by avishaan** [jason0x43/alfred-toggl#12]
I think being able to "continue" the previous timer could be a really good feature. I often find myself "pausing" a timer for a few minutes only to restart the same one. Being able to do `tgl continue` would be amazing. Here is a screenshot of the feature in the built in app i'm referring to. 

![image](https://cloud.githubusercontent.com/assets/5360982/10561600/52f462ba-74e5-11e5-9ed9-a5d755e67de8.png)

Alternatively the command could be `tgl timers continue` but `tgl continue` would be significantly more useful.

Amazing workflow btw.

**Comment by jason0x43** [comment]
This is currently handled globally (and has for a while) via the 'DurationOnly' option. When this option is true, time entries operate in 'duration' mode, where continuing one simply extends its time. In the other, default mode of operation, restarting/continuing a timer creates a new time entry with the same description, project, etc.

I'll add a mod key to allow continuing any time entry.
