### ISSUE TITLE
I'm not able to "Tab" the options

### ISSUE THREAD

**Issue by float-mode** [jason0x43/alfred-toggl#15]
I'm just starting to use it, but the tab button doesnt work for some reason with my Alfred... I checked settings in alfred but didnt find anything about the Tab button or tabbing in general. I've used the arrows in Alfred to navigate folderst, etc.. 
For this workflow Tab works sometimes if pressed along with the Alt key as I have alt assigned for the Action commands... but it doesnt work all the time I find... Any tips or how can I make this  Tgl Workflow work with tabbing (as conceived).
Cheers

**Comment by jason0x43** [comment]
So, the way tabbing works in this workflow is simply for auto-completion. So, if you type `tgl`, you should see a list of actions. Start typing one of them, then press `tab` and the top item in the list should be completed. Tabbing doesn't cycle through options, it just completes the currently selected one. Although, given how the Enter key selects, I suppose tab cycle through the current list.

**Comment by jason0x43** [comment]
Hi, just checking up -- is this still an issue?

**Comment by jason0x43** [comment]
Closing since there haven't been any updates
