### ISSUE TITLE
Stay on status "Talking to Toggle" without anymore effect

### ISSUE THREAD

**Issue by vmingam** [jason0x43/alfred-toggl#16]
Hi Jason,
Thx for you work on this great workflow.
Since today (10th of March 2016) the connection with **Toggle** seems broken, no more option comes while typing _tgl_ command in Alfred. 
Thank you for your help.
Regards,
Vince

**Comment by jason0x43** [comment]
Hi, just checking up -- is this still an issue?

**Comment by vmingam** [comment]
Nop! Everything is OK
Thank you.

Le dim. 15 mai 2016 à 14:42, Jason Cheatham notifications@github.com a
écrit :
