### ISSUE TITLE
Commands don't do anything after login

### ISSUE THREAD

**Issue by thilorichter-optimizely** [jason0x43/alfred-toggl#17]
Hi,

I managed to log in and get all the commands in alfred but pressing enter on any doesn't do anything. If I do tgl -> timers it just doesn't do anything. It doesn't even close the alfred window or give me an error message. Just nothing. The same with any other command except logout and options. I can login and logout but do nothing else.

I used the alfred debug dialog but get no errors whatsoever. Looks like this (I replaced some personal information):

Starting debug for 'Toggl'

[STDERR: alfred.workflow.input.scriptfilter] 2016/04/08 11:48:03 Using config file /Users/trichter/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2016/04/08 11:48:03 Using cache file /Users/..../Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2016/04/08 11:48:03 loaded config: {....  true 0 false}
2016/04/08 11:48:03 loaded cache
[alfred] 2016/04/08 11:48:03 args: []string{"./alfred-toggl", "tell", ""}
[alfred] 2016/04/08 11:48:03 op: 'tell'
[alfred] 2016/04/08 11:48:03 keyword: ''
[alfred] 2016/04/08 11:48:03 query: ''
[alfred] 2016/04/08 11:48:03 prefix: ' '
[alfred] 2016/04/08 11:48:03 skip: 'map[]'
[alfred] 2016/04/08 11:48:03 sorting by keyword:
[STDERR: alfred.workflow.input.scriptfilter] 2016/04/08 11:48:17 Using config file /Users/..../Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2016/04/08 11:48:17 Using cache file /Users/.../Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2016/04/08 11:48:17 loaded config: {... true 0 false}
2016/04/08 11:48:17 loaded cache
[alfred] 2016/04/08 11:48:17 args: []string{"./alfred-toggl", "tell", ""}
[alfred] 2016/04/08 11:48:17 op: 'tell'
[alfred] 2016/04/08 11:48:17 keyword: ''
[alfred] 2016/04/08 11:48:17 query: ''
[alfred] 2016/04/08 11:48:17 prefix: ' '
[alfred] 2016/04/08 11:48:17 skip: 'map[]'
[alfred] 2016/04/08 11:48:17 sorting by keyword:

I use Alfred 2.8.2.

**Comment by jason0x43** [comment]
If you type `tgl timers`, the log should be showing 'timers' as the keyword, so something's not right there.

Open a command prompt and cd to the workflow directory. (You can find the workflow directory by right clicking on the workflow in the sidebar of Alfred's settings and clicking "Show in Finder".) Run the following command:

```
./alfred-toggl tell timers
```

What output do you see?

**Comment by thilorichter-optimizely** [comment]
I got the below + a big reply from the server with all the timers. And now when I do it through Alfred itself it suddenly works too. It seems that calling it from the terminal somehow "fixed" it. Doesn't make sense really. 
So it now works. There is another thing which I realised though. Using "tgl -> projects" and then typing a project name doesn't always filter the list. 90% of the time starting to type a project name doesn't do anything. It's quite buggy. We use several hundred projects and I wont to select one and start a timer. The filtering is quite important.

Thanks!

[alfred] 2016/04/18 09:23:34 args: []string{"./alfred-toggl", "tell", "timers"}
[alfred] 2016/04/18 09:23:34 op: 'tell'
[alfred] 2016/04/18 09:23:34 keyword: 'timers'
[alfred] 2016/04/18 09:23:34 query: ''
[alfred] 2016/04/18 09:23:34 prefix: 'timers '
[alfred] 2016/04/18 09:23:34 skip: 'map[]'
[alfred] 2016/04/18 09:23:34 checking timers
2016/04/18 09:23:34 Refreshing cache...
2016/04/18 09:23:34 GETing from URL: https://toggl.com/api/v8/me?with_related_data=true
2016/04/18 09:23:35 got account: to....

**Comment by jason0x43** [comment]
Regarding project filtering, are you using the latest release ([1.1.6](https://github.com/jason0x43/alfred-toggl/releases/tag/v1.1.6))? That significantly improved input filtering.

**Comment by jason0x43** [comment]
Hi, just checking up -- is this still an issue?

**Comment by jason0x43** [comment]
Closing this to clean up the list. If it's still a problem, feel free to re-open the issue.
