### ISSUE TITLE
Can I go straight to 'report' from a hotkey or a keyword?

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/alfred-toggl#19]

**Comment by jason0x43** [comment]
The `report` command will show total hours logged today, yesterday, and this week. It really should support an arbitrary date, but I haven't implemented that yet.

**Comment by jason0x43** [comment]
Oh, sorry, I didn't fully read the issue. Yeah, there isn't a direct keyword for that at the moment, but I'll look into adding one.

**Comment by nikivdev** [comment]
Yeah, I understand that. However is there a way to go from hotkey/input to show 'report' straight away without going to 'tgl' main window first and getting report from there?

**Comment by jason0x43** [comment]
In the version in master there are now keywords for most major operations. For example, there is now a `tgr` keyword to access reports. To get a report for the current week, you would type `tgr week` -> Enter. To get a report for an arbitrary day, type something like `tgr 7/21` -> Enter.

**Comment by nikivdev** [comment]
Can you add the version to releases? Thank you. :)

**Comment by jason0x43** [comment]
I haven't made the release yet; I wanted to update the README first since the workflow's operation has changed a bit.
