### ISSUE TITLE
Deleted projects remain in list of projects (tgl projects)

### ISSUE THREAD

**Issue by shrop** [jason0x43/alfred-toggl#21]
Love this workflow! Thanks for creating it. I rely on it everyday.

One thing that bugs me is that delete projects in Toggl still appear in the list of projects when I list them with `tgl projects`.

Some notes:
- I don't get those old projects when request the list of projects using API methods from https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md#get-workspace-projects. 
- I have tried doing `togl reset` and I get an error. "Error: unknown command ". Maybe a change for Alfred 3.
- I delete the workflow, the workflow caches and settings, but when I reinstall, they still appear in the list. 
- I must be missing a cache somewhere. Any thoughts on this?

Thanks!

**Comment by jason0x43** [comment]
The workflow currently only considers the "active" flag, and doesn't pay attention to whether the project is deleted. I wrongly assumed a deleted project would also be made inactive, and didn't have any deleted projects when I last released the workflow. This will be fixed in the next release.

**Comment by shrop** [comment]
@jason0x43 ahh, that makes sense!

Thanks for working on this for the next release. If anything, my change to tour the codebase got me interested in Go! :)

**Comment by jason0x43** [comment]
This is fixed in master

**Comment by shrop** [comment]
thank you @jason0x43!
