### ISSUE TITLE
How can I clean up fully 'projects' tab

### ISSUE THREAD

**Issue by nikivdev** [jason0x43/alfred-toggl#28]
I have a lot of projects that I have not used for a long time and have deleted in Toggl and yet they show : 

![2016-10-08 at 23 21](https://cloud.githubusercontent.com/assets/6391776/19216007/fdcf3e58-8dad-11e6-9f73-0b7986240f89.png)

Is there a way to delete them? I just want to have projects I am actually currently working on to show and ideally sort this list by projects worked most recently. Can this be done?

Thank you for making this workflow. It is superbly well done.

**Comment by jason0x43** [comment]
Is this the list you're seeing for the main projects list (`tgp` or `tgl projects`)? I updated the workflow in v2 to only show "active" projects (ones that haven't been archived) in the main list. Prior to that the list would show every project it downloaded from Toggl, which would include old, archived projects.

**Comment by nikivdev** [comment]
Oh thank you, that's another point that I wanted to mention that was improved. I can finally go through my projects. This is great.
