### ISSUE TITLE
Error: Unknown command "."

### ISSUE THREAD

**Issue by jakubjanousek** [jason0x43/alfred-toggl#3]
The workflow throws Error: Unknown command "." when I try to run any action. Not sure why it happened, it may have to do something with me changing password or API token to toggl.

Deleting the workflow doesn't help as it shows me all the options (like timer, sync etc.) directly after adding it again (no password prompt)

Is there a way to completely remove all the workflow data?

**Comment by jason0x43** [comment]
A new `reset` command was added in [release 1.1.0](https://github.com/jason0x43/alfred-toggl/releases/tag/v1.1.0) to reset the workflow to a clean state. Give that a try.

**Comment by jakubjanousek** [comment]
It didn't work at first and threw Unknown command errors when I ran the reset command.

On the fifth try it finally got through and the workflow works perfectly now. Thanks

**Comment by jason0x43** [comment]
Odd...but glad to hear it's working!
