### ISSUE TITLE
In Reports at least, 1st day seems to always be Sunday whatever the setting

### ISSUE THREAD

**Issue by godbout** [jason0x43/alfred-toggl#31]
My setting in toggl is first day on Monday, but in the weekly report the "past" Sunday is included too. If I'm not mistaken, it is incorrect.

**Comment by jason0x43** [comment]
The weekly report generated by the workflow is currently completely separate from Toggl's settings. It would make sense to use them, though.

**Comment by godbout** [comment]
Or in the options, first day of the week? Currently whether toggl settings or computer settings, first day seems to be Sunday, except if I'm missing something.

**Comment by jason0x43** [comment]
You're correct, it is Sunday (it's always Sunday right now).
