### ISSUE TITLE
Create a new time entry when similarly called entries exist

### ISSUE THREAD

**Issue by dasilvacontin** [jason0x43/alfred-toggl#35]
e.g. `tgt lunch`, where you have entries like `get lunch`. I can't manage to.

Great workflow though, thanks! :)

**Comment by jason0x43** [comment]
What do you mean? Like, you want to create a new entry with the same name?

**Comment by dasilvacontin** [comment]
@jason0x43 No, I want to create an entry with the name `lunch`. But I already have other entries mentioning `lunch`. I get no option to create a new one, just to select one of the already existing ones.

**Comment by jason0x43** [comment]
Ah, yes, that's an issue.

**Comment by jason0x43** [comment]
Fixed in [v2.5.0](https://github.com/jason0x43/alfred-toggl/releases/tag/v2.5.0)

**Comment by dasilvacontin** [comment]
Thanks! <3
