### ISSUE TITLE
CMD+Enter on 'New entry option' does nothing

### ISSUE THREAD

**Issue by dasilvacontin** [jason0x43/alfred-toggl#37]
Steps:
1. type `tgt asdkfaskdg`. New entry is only option, highlighted by default.
2. do CMD+Enter. Notice Alfred closes but workflow didn't start tracking.

Expected:
Start tracking

**Comment by jason0x43** [comment]
The Cmd modifier currently only applies to existing entries. It's used to differentiate between editing an entry (which is what happens when you just press Enter) and restarting an entry.

I can see how having Cmd start a new entry would make sense, though. I'll add that.

**Comment by dasilvacontin** [comment]
Thanks! <3 With that change you can blindly do CMD+Enter regardless of the case.

**Comment by jason0x43** [comment]
This has been added in [release 2.6.0](https://github.com/jason0x43/alfred-toggl/releases/tag/v2.6.0).

**Comment by dasilvacontin** [comment]
Thanks!
