### ISSUE TITLE
Create timer from existing project?

### ISSUE THREAD

**Issue by ghost** [jason0x43/alfred-toggl#40]
I don't see how to select a project and start the timer for that project. I've read the README and still can't seem to find how to do it.

Suggestions?

**Comment by jason0x43** [comment]
The process is actually to create a timer and then select the project for it. A typical flow would be

1. `tgt time entry name<Enter>`
2. select a project from the list and press `<Enter>`

**Comment by ghost** [comment]
Yep. I figured it out. Thanks @jason0x43. Going to close this.
