### ISSUE TITLE
Can you fix adding tags and remove the last tag of a time entry?

### ISSUE THREAD

**Issue by wanicode** [jason0x43/alfred-toggl#41]
When i try to add a tag, hitting enter does nothing.
And when i try to remove the last tag of a time entry, it doesn't get deleted.

**Comment by jason0x43** [comment]
> When i try to add a tag, hitting enter does nothing.

Could you provide a bit more detail here (like, is this what you're trying)?

1. `tgt something` to select a time entry, press enter
2. Select `tags` and press enter
3. Select a particular unchecked tag in the tags list and press enter

> And when i try to remove the last tag of a time entry, it doesn't get deleted.

This appears to be a bug.

**Comment by wanicode** [comment]
No, for Number 1 i try to add a new Tag:

1. tgl tag + enter
2. someething (new tag label beneath)
3. hit enter does nothing in this case

(just to be clear, this is a very minor bug, the other one is much worse imo.)

**Comment by jason0x43** [comment]
Ah, I see. I thought the original issue was referring to adding a tag to an issue, not adding/creating an entirely new tag. I see that one.

The other issue has been fixed in release 2.6.1.

**Comment by jason0x43** [comment]
Tag functionality has been fully implemented in [release 2.7.0](https://github.com/jason0x43/alfred-toggl/releases/tag/v2.7.0).

**Comment by wanicode** [comment]
Wow nice, that was fast. Thank you very very much :)
