### ISSUE TITLE
TGT no longer showing all timers

### ISSUE THREAD

**Issue by timbroder** [jason0x43/alfred-toggl#42]
I think this started happening with the 2.7.0 which I upgraded to this morning.

TGT is only showing new timers that I've started with this workflow instead of all my timers. 

I have tried resetting data and logging back in using the API key.

What else can I try? Thanks

**Comment by jason0x43** [comment]
If you create a timer in the Toggl web interface (or somewhere outside the workflow) and then force the workflow to download new data (`tgs`), does it still not show your new timer?

**Comment by timbroder** [comment]
Ah ok, interesting. If I start an old timer (I differentiate by description) this workflow now sees it. 

Is there a duration where it won't see timers that haven't been started in a few days?

Thanks

**Comment by jason0x43** [comment]
Currently the workflow uses the Toggl API's default limits for time entry requests, which are 9 days and up to 1000 time entries.

There is an open issue for monthly reports  (#38) which would probably take care of this; I just haven't gotten to it yet.

**Comment by timbroder** [comment]
Gotcha. It's very possible it's been 9+ days as I was out part of last week.

I'll close this and re-open if I notice otherwise

Thanks for this workflow, I wouldn't be using Toggl at all if it didn't exist
