### ISSUE TITLE
Manual Project refresh?

### ISSUE THREAD

**Issue by kporangehat** [jason0x43/alfred-toggl#46]
Loving this workflow... kudos!🥇 

I have Toggl integrated with an internal system that creates projects automatically for me based on my current work. But this information doesn't get updated locally in the workflow immediately. Is there a way to trigger a refresh of the Toggl projects so I can pickup changes immediately?

thanks!

**Comment by jason0x43** [comment]
The `status` command (`tgs`) will update the cached data immediately, including the projects list. I could also make the refresh time configurable that that would help. Currently the workflow will refresh cached data when a command is run if the last time the cache was refreshed was more than 5 minutes ago.

**Comment by kporangehat** [comment]
That's great info! The `tgs` command should serve my purpose well. I think a 5 minute interval seems reasonable for most usage otherwise. Thanks!
