### ISSUE TITLE
Don't throw away new timer when Cmd-Ret'ing project

### ISSUE THREAD

**Issue by Peeja** [jason0x43/alfred-toggl#48]
First off, I *love* alfred-toggl. I use it all day long. Thank you so much for it.

I typically add a project when I'm creating a new timer, and to do that I type the description for the timer and press Cmd-Return, which takes me to the list of projects. If I select one and press Return, all is well, and my timer starts. If I press *Cmd*-Return, which I do a good chunk of the time because I just used it, it doesn't start my timer, it just silently fails. Since Cmd-Return isn't used for anything else there, could it act exactly like a normal Return?

**Comment by jason0x43** [comment]
Glad to hear it's working well for you!

Hmmm...pressing Cmd-Return after typing a timer description should automatically create the timer with no project, no take you to the project list (just pressing Return should do that). In any case, though, I agree that pressing Cmd-Return probably shouldn't silently fail, and it makes sense for it to act like Return in that case (at least unless/until there is some other use for it). I'll add that in the next release.

**Comment by jason0x43** [comment]
Fixed in https://github.com/jason0x43/alfred-toggl/releases/tag/v2.11.0

**Comment by jason0x43** [comment]
Oh, I see what you meant. I've had the "AskForProject" option turned on for so long I forgot that wasn't the default behavior. :)

**Comment by Peeja** [comment]
Thank you!
