### ISSUE TITLE
Error Command ''

### ISSUE THREAD

**Issue by raafamaia** [jason0x43/alfred-toggl#5]
Hey, I'm trying to add a project to an existing timer, like 

"tgl timers 191710250 » project » Reading Stuff⁣"

and I keep getting this error

Error: Unknown Command '' 

Here's the full debugging file:

[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/19 10:46:16 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:16 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:16 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:16 loaded cache
2015/01/19 10:46:16 args: []string{"./alfred-toggl", "tell", ""}
2015/01/19 10:46:16 op: 'tell'
2015/01/19 10:46:16 kind: ''
2015/01/19 10:46:16 query: ''
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/19 10:46:18 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:18 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:18 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:18 loaded cache
2015/01/19 10:46:18 args: []string{"./alfred-toggl", "tell", "timers "}
2015/01/19 10:46:18 op: 'tell'
2015/01/19 10:46:18 kind: 'timers'
2015/01/19 10:46:18 query: ''
2015/01/19 10:46:18 Refreshing cache...
2015/01/19 10:46:18 GETing from URL: https://toggl.com/api/v8/me?with_related_data=true
2015/01/19 10:46:19 got account: toggl.Account{Data:struct { ApiToken string "json:\"api_token\""; Timezone string "json:\"timezone\""; Id int "json:\"id\""; Workspaces []toggl.Workspace "json:\"workspaces\""; Projects []toggl.Project "json:\"projects\""; Tags []toggl.Tag "json:\"tags\""; TimeEntries []toggl.TimeEntry "json:\"time_entries\"" }{ApiToken:"48a5101f8fc5eb51fd17810fbd7c3cc3", Timezone:"America/Sao_Paulo", Id:1507438, Workspaces:[]toggl.Workspace{toggl.Workspace{Id:768645, RoundingMinutes:0, Rounding:1, Name:"Raafamaia's workspace"}}, Projects:[]toggl.Project{toggl.Project{Wid:768645, Id:8221457, Name:"Angular.js"}, toggl.Project{Wid:768645, Id:8221339, Name:"Democracy.app"}, toggl.Project{Wid:768645, Id:8184451, Name:"GitHub"}, toggl.Project{Wid:768645, Id:8182386, Name:"JavaScript OOP"}, toggl.Project{Wid:768645, Id:8245656, Name:"PhoneGap"}, toggl.Project{Wid:768645, Id:8221462, Name:"Reading Stuff"}, toggl.Project{Wid:768645, Id:8236729, Name:"Thinkster.io"}, toggl.Project{Wid:768645, Id:8184455, Name:"Time Off"}}, Tags:[]toggl.Tag(nil), TimeEntries:[]toggl.TimeEntry{toggl.TimeEntry{Wid:768645, Id:189439309, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc208298640), Start:(_time.Time)(0xc208298600), Tags:[]string(nil), Duration:3680}, toggl.TimeEntry{Wid:768645, Id:189453563, Pid:8184451, Description:"GitHub", Stop:(_time.Time)(0xc2082987e0), Start:(_time.Time)(0xc2082987a0), Tags:[]string(nil), Duration:1073}, toggl.TimeEntry{Wid:768645, Id:189483142, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc2082989a0), Start:(_time.Time)(0xc208298940), Tags:[]string(nil), Duration:1645}, toggl.TimeEntry{Wid:768645, Id:189766431, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc208298b80), Start:(_time.Time)(0xc208298b40), Tags:[]string(nil), Duration:3958}, toggl.TimeEntry{Wid:768645, Id:189794114, Pid:8184455, Description:"League Of Legends", Stop:(_time.Time)(0xc208298dc0), Start:(_time.Time)(0xc208298d60), Tags:[]string(nil), Duration:12}, toggl.TimeEntry{Wid:768645, Id:189844687, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc208298f80), Start:(_time.Time)(0xc208298f40), Tags:[]string(nil), Duration:1014}, toggl.TimeEntry{Wid:768645, Id:189870589, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc2082991c0), Start:(_time.Time)(0xc208299160), Tags:[]string(nil), Duration:2601}, toggl.TimeEntry{Wid:768645, Id:190064035, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc208299320), Start:(_time.Time)(0xc2082992e0), Tags:[]string(nil), Duration:2349}, toggl.TimeEntry{Wid:768645, Id:190228524, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc2082994c0), Start:(_time.Time)(0xc208299460), Tags:[]string(nil), Duration:2435}, toggl.TimeEntry{Wid:768645, Id:190414681, Pid:8221462, Description:"AirPair", Stop:(_time.Time)(0xc2082996a0), Start:(_time.Time)(0xc208299640), Tags:[]string(nil), Duration:803}, toggl.TimeEntry{Wid:768645, Id:190446019, Pid:8182386, Description:"JavaScript OOP", Stop:(_time.Time)(0xc208299840), Start:(_time.Time)(0xc208299800), Tags:[]string(nil), Duration:2647}, toggl.TimeEntry{Wid:768645, Id:190464084, Pid:8184451, Description:"GitHub", Stop:(_time.Time)(0xc208299a40), Start:(_time.Time)(0xc2082999e0), Tags:[]string(nil), Duration:257}, toggl.TimeEntry{Wid:768645, Id:190466035, Pid:8221462, Descr
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/19 10:46:22 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:22 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:22 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:22 loaded cache
2015/01/19 10:46:22 args: []string{"./alfred-toggl", "tell", "timers 191710250 » "}
2015/01/19 10:46:22 op: 'tell'
2015/01/19 10:46:22 kind: 'timers'
2015/01/19 10:46:22 query: '191710250 » '
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/19 10:46:25 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:25 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:25 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:25 loaded cache
2015/01/19 10:46:25 args: []string{"./alfred-toggl", "tell", "timers 191710250 » project » "}
2015/01/19 10:46:25 op: 'tell'
2015/01/19 10:46:25 kind: 'timers'
2015/01/19 10:46:25 query: '191710250 » project » '
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 2015/01/19 10:46:30 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:30 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:30 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:30 loaded cache
2015/01/19 10:46:30 args: []string{"./alfred-toggl", "tell", "timers 191710250 » project » Reading Stuff\u2063"}
2015/01/19 10:46:30 op: 'tell'
2015/01/19 10:46:30 kind: 'timers'
2015/01/19 10:46:30 query: '191710250 » project » Reading Stuff⁣'
[ERROR: alfred.workflow.action.script] Code 0: 2015/01/19 10:46:34 Using config file /Users/rafaelmaia/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/01/19 10:46:34 Using cache file /Users/rafaelmaia/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/01/19 10:46:34 loaded config: {48a5101f8fc5eb51fd17810fbd7c3cc3 false}
2015/01/19 10:46:34 loaded cache
2015/01/19 10:46:34 args: []string{"./alfred-toggl", "do", ""}
2015/01/19 10:46:34 op: 'do'
2015/01/19 10:46:34 kind: ''
2015/01/19 10:46:34 query: ''

**Comment by jason0x43** [comment]
Hmmm...it looks like the project assignment command isn't being generated properly. I'll look into it.

**Comment by lrobeson** [comment]
I'm having the same issue. I also get that error if I try to run "tgl logout" or "tgl reset".

**Comment by jason0x43** [comment]
Version 1.1.1 adds the ability to update the project for an existing time entry. Try it and let me know if you experience any issues.

**Comment by lrobeson** [comment]
v1.1.1 isn't working for me, here's some debug info when I try to run "tgl timers":

```
2015/02/17 12:39:19 args: []string{"./alfred-toggl", "tell", "timers"}
2015/02/17 12:39:19 op: 'tell'
2015/02/17 12:39:19 keyword: 'timers'
2015/02/17 12:39:19 query: ''
2015/02/17 12:39:19 prefix: 'timers '
2015/02/17 12:39:19 skip: 'map[]'
2015/02/17 12:39:19 checking timers
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x17afd]

goroutine 1 [running]:
main.TimeEntryFilter.Items(0xc208057075, 0x7, 0x0, 0x0, 0xc2080c8000, 0xd, 0x10, 0x5b2a68, 0xc20800bb00)
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/alfred-toggl/time_entry.go:320 +0x49ad
main.(*TimeEntryFilter).Items(0x5049d8, 0xc208057075, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:22 +0xf8
github.com/jason0x43/go-alfred.(*Workflow).Run(0x4fc0c0, 0xc208091e80, 0x11, 0x11)
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/go-alfred/main.go:175 +0x168f
main.main()
    /Users/jason/Documents/Programming/go/src/github.com/jason0x43/alfred-toggl/main.go:77 +0x1114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by jason0x43** [comment]
My quest to eliminate as many uses of pointers as possible continues... Update coming soon.

**Comment by raafamaia** [comment]
project assignment command works now!

**Comment by jason0x43** [comment]
@lrobeson I moved your problem description to a new issue (#6).
