### ISSUE TITLE
Cannot stop timer if it was stopped in toggl

### ISSUE THREAD

**Issue by piscopoc** [jason0x43/alfred-toggl#50]
I manually stopped a timer in toggl and now I can't get a new timer starter within Alfred. Is there a way to reset the workflow to start accepting new time entries again?

**Comment by jason0x43** [comment]
Run `tgs` -- that will sync the state of the workflow with Toggl, including any currently running (or not) timer.

**Comment by piscopoc** [comment]
Excellent, thanks!
