### ISSUE TITLE
Switching what starts a task

### ISSUE THREAD

**Issue by ryanjm** [jason0x43/alfred-toggl#52]
When using `tgt`, instead of hitting ⌘+enter to start a task, I'd like to just hit enter. Then if I want to edit it, then I'd want to hit ⌘+enter.

I haven't written Go before, but can you point me to where this setting is? I'd be happy to fork it and set it up for myself. Otherwise, it'd also be a nice generalized setting. 😄

**Comment by jason0x43** [comment]
Assuming you're still interested in this...

The modifier actions are defined when creating list items using the `AddMod` item method. For example, a timer item in the list generated when you type `tgt` is defined to have a [default action](https://github.com/jason0x43/alfred-toggl/blob/master/time_entry.go#L154) and a [modifier action for ⌘](https://github.com/jason0x43/alfred-toggl/blob/master/time_entry.go#L167).

The workflow actually used to work as you describe, but after developing a number of similar workflows it seemed like having ⌘+Enter do something while having just Enter open a menu led to the most consistent behavior.

**Comment by ryanjm** [comment]
Thanks!
