### ISSUE TITLE
Workflow shows error in Catalina after new installation

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/alfred-toggl#55]
<img width="532" alt="Screen Shot 2020-02-12 at 9 26 56 AM" src="https://user-images.githubusercontent.com/1042866/74343930-d9485800-4d79-11ea-9ac6-986e2fac5093.png">

**Comment by jason0x43** [comment]
https://github.com/mitchellh/gon would probably work

**Comment by rogatty** [comment]
As a workaround:
- Right-click on Toggl workflow in Alfred
- Open in Finder
- Right-click on alfred-toggle
- Open
- Confirm

**Comment by Leland** [comment]
FYI for the above workaround, you will need to re-permission on each macOS update.

Getting a notarization workflow setup would be great

**Comment by jason0x43** [comment]
I looked more into notarization. Unfortunately, it seems that you need a paid Apple Developer account to notarize applications (a free account isn't sufficient). I only have a free account since I don't publish any binaries other than a couple of Alfred workflows. It may be time to switch back to Python...

**Comment by zmoog** [comment]
> Unfortunately, it seems that you need a paid Apple Developer account to notarize applications (a free account isn't sufficient)

Yep, you need an Apple Developer account worth $100/year to code-sign and notarize an application for macOS Catalina 😞

**Comment by jason0x43** [comment]
I'm tempted to just port this back to an interpreted language, but I would miss the speed.

**Comment by jason0x43** [comment]
I've attempted to sign and notarize the binary in the v2.12.0 release. (I finally got a real developer account 😁) Apple's notarization process isn't really geared towards standalone binaries, but theoretically it's good. I'd be interested to hear if it works.

**Comment by Leland** [comment]
@jason0x43 yay, worked perfectly! Thanks much. Happy to throw some cash your way to defray the cost

**Comment by vitorgalvao** [comment]
Looks like issue can be closed, the signed binary works.
