### ISSUE TITLE
“alfred-toggl” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by rasulkireev** [jason0x43/alfred-toggl#57]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/8257474/89804073-ac46e900-db01-11ea-8dbd-b2a37ae1b320.png">

Anyone ran into this issue? Any solutions?

**Comment by jason0x43** [comment]
See https://github.com/jason0x43/alfred-toggl/issues/55#issuecomment-590196612

**Comment by rasulkireev** [comment]
Thanks Jason
