### ISSUE TITLE
toggl track: 502 Bad Gateway

### ISSUE THREAD

**Issue by lhoffjann** [jason0x43/alfred-toggl#58]
Seems like the workflow doesnt work anymore since toggl changed to toggl track. only thing i get is the Bad Gateway Error

**Comment by Domonlee** [comment]
This because toggl change their API url. I just send a PR to **go-toggl** repo, waiting for Jason0x43 approve.

**Comment by robertwijas** [comment]
Just linking the PR mentioned by @Domonlee: jason0x43/go-toggl#14.

**Comment by robertwijas** [comment]
Looks like they restored old API urls. Workflow seems to work for me now.

**Comment by Domonlee** [comment]
> Looks like they restored old API urls. Workflow seems to work for me now.

Yes. The old API URL works fine now 💯

**Comment by Leland** [comment]
This can be closed now
