### ISSUE TITLE
Update API endpoint to `api.track.toggl.com` - June 30th 2021 deadline

### ISSUE THREAD

**Issue by jjarava** [jason0x43/alfred-toggl#60]
Hi!

Very happy user of this workflow (thanks!)

I just recently got an email from Toggle reminding me about the API endpoint changes from their branding change. Basically the API endpoint changes to `api.track.toggl.com`.

For reference, the email in its entirety says:

>Hi there, 
>
>We are reaching out because we detected API usage coming from your Toggl Track account using the [www.toggl.com](https://www.toggl.com) (or [toggl.com](https://toggl.com)) domain. 
>
>After last year's rebranding, we released [api.track.toggl.com](https://api.track.toggl.com) as our new domain for API usage. These changes were communicated via newsletter and the [following blog post](https://toggl.com/blog/api-documentation-change). The [API Docs](https://github.com/toggl/toggl_api_docs) were also updated to reflect the domain changes. 
>
>We want to inform you that the usage of [www.toggl.com](https://www.toggl.com) (or [toggl.com](https://toggl.com)) domain for the API will be **dropped after 'June 30th 2021'**. 
>
>We encourage you to perform the switch to [api.track.toggl.com](https://api.track.toggl.com) as soon as possible in order to prevent disruption. 
>
>Best wishes, 
>The Toggl Track Team 
>support@track.toggl.com 

Hope this helps

**Comment by Leland** [comment]
Should be closed by https://github.com/jason0x43/alfred-toggl/releases/tag/v2.12.0

**Comment by jason0x43** [comment]
Good catch -- thanks!
