### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by nuynait** [jason0x43/alfred-toggl#7]
after I enter the api token, then type tgl in the alfred, it still have only two option, login and token. If I press login, it gives me a text inbox to enter the email address. I enter the email address, and it didn't ask me for the password

I have no way to login in to the toggl in this workflow. Anyidea why is this happening?

**Comment by nuynait** [comment]
I tried both 1.1.2 and 1.1.1 version.
System: Yosemite

**Comment by nuynait** [comment]
Here is the error message

[STDERR: alfred.workflow.input.scriptfilter] 2015/02/18 01:20:55 Using config file /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/02/18 01:20:55 Using cache file /Users/tshan/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/02/18 01:20:55 Error loading config: open /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2015/02/18 01:20:55 loaded config: { false}
2015/02/18 01:20:55 loaded cache
2015/02/18 01:20:55 args: []string{"./alfred-toggl", "tell", "to"}
2015/02/18 01:20:55 op: 'tell'
2015/02/18 01:20:55 keyword: 'to'
2015/02/18 01:20:55 query: ''
2015/02/18 01:20:55 prefix: 'to '
2015/02/18 01:20:55 skip: 'map[]'
2015/02/18 01:20:55 score for token vs to: 0.18
[ERROR: alfred.workflow.action.script] 2015/02/18 01:20:56 Using config file /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/02/18 01:20:56 Using cache file /Users/tshan/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/02/18 01:20:56 Error loading config: open /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2015/02/18 01:20:56 loaded config: { false}
2015/02/18 01:20:56 loaded cache
2015/02/18 01:20:56 args: []string{"./alfred-toggl", "do", "token"}
2015/02/18 01:20:56 op: 'do'
2015/02/18 01:20:56 keyword: 'token'
2015/02/18 01:20:56 query: ''
2015/02/18 01:20:56 prefix: 'token '
2015/02/18 01:20:56 skip: 'map[]'
2015/02/18 01:20:58 User didn't click OK

**Comment by jason0x43** [comment]
From the log, it looks like you're not clicking "Ok" on the token entry dialog (at least not when you generated that set of log statements).

**Comment by nuynait** [comment]
https://www.youtube.com/watch?v=ott09QFK5Ks
Here is a screenshot I recorded to prove that I truly pressed the "Ok" on the token entry dialog.

This is an excellent tool that I need for my daily life. I hope that you can help me get it working.
Really appreciate you time. Thanks a lot.

**Comment by jason0x43** [comment]
Hmmm...  That's a new one. Let me look into it. I may have some debugging steps for you to try.

**Comment by nuynait** [comment]
no problem. feel free to tell me what I should do

**Comment by jason0x43** [comment]
I posted a new version, [1.1.3](https://github.com/jason0x43/alfred-toggl/releases/tag/v1.1.3), that has some improved dialog handling code. Try that and let me know if it works.

**Comment by nuynait** [comment]
It still not working.

Here is the debugging message when I enter the api token:
Starting debug for 'Toggl'

[STDERR: alfred.workflow.input.scriptfilter] 2015/02/21 16:04:02 Using config file /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/02/21 16:04:02 Using cache file /Users/tshan/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/02/21 16:04:02 Error loading config: open /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2015/02/21 16:04:02 loaded config: { false}
2015/02/21 16:04:02 loaded cache
2015/02/21 16:04:02 args: []string{"./alfred-toggl", "tell", ""}
2015/02/21 16:04:02 op: 'tell'
2015/02/21 16:04:02 keyword: ''
2015/02/21 16:04:02 query: ''
2015/02/21 16:04:02 prefix: ' '
2015/02/21 16:04:02 skip: 'map[]'
[STDERR: alfred.workflow.input.scriptfilter] 2015/02/21 16:04:03 Using config file /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/02/21 16:04:03 Using cache file /Users/tshan/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/02/21 16:04:03 Error loading config: open /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2015/02/21 16:04:03 loaded config: { false}
2015/02/21 16:04:03 loaded cache
2015/02/21 16:04:03 args: []string{"./alfred-toggl", "tell", ""}
2015/02/21 16:04:03 op: 'tell'
2015/02/21 16:04:03 keyword: ''
2015/02/21 16:04:03 query: ''
2015/02/21 16:04:03 prefix: ' '
2015/02/21 16:04:03 skip: 'map[]'
[ERROR: alfred.workflow.action.script] 2015/02/21 16:04:05 Using config file /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json
2015/02/21 16:04:05 Using cache file /Users/tshan/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.jason0x43.alfred-toggl/cache.json
2015/02/21 16:04:05 Error loading config: open /Users/tshan/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-toggl/config.json: no such file or directory
2015/02/21 16:04:05 loaded config: { false}
2015/02/21 16:04:05 loaded cache
2015/02/21 16:04:05 args: []string{"./alfred-toggl", "do", "token"}
2015/02/21 16:04:05 op: 'do'
2015/02/21 16:04:05 keyword: 'token'
2015/02/21 16:04:05 query: ''
2015/02/21 16:04:05 prefix: 'token '
2015/02/21 16:04:05 skip: 'map[]'
2015/02/21 16:04:05 running script:
2015/02/21 16:04:05 tell application "Alfred 2"
              activate
              set alfredPath to (path to application "Alfred 2")
              set alfredIcon to path to resource "appicon.icns" in bundle (alfredPath as alias)
              display dialog "API token:" with title "Toggl" default answer "" buttons {"Cancel", "Ok"} default button "Ok" with icon alfredIcon
          end tell
2015/02/21 16:04:06 User didn't click OK

_I promise - I did press ok_

**Comment by jason0x43** [comment]
I believe you. :)  Try this: open Script Editor (in `/Applications/Utilities`), paste in the script above (everything from `tell application "Alfred 2"` to `end tell`), and run the script. It should pop up a dialog asking you for your API token. Enter anything and click "Ok". What is shown in the Result panel of the Script Editor? I get:

![Screenshot](https://s3.amazonaws.com/f.cl.ly/items/3g17123n1H3o1z2G2l13/Image%202015-02-21%20at%208.30.54%20PM.png)

**Comment by nuynait** [comment]
This is what I got. Seems that the script is working correctly
![finder finder today at 9 33 42 pm](https://cloud.githubusercontent.com/assets/2152195/6317138/72775f0a-ba11-11e4-89c6-ed2fa24ec733.png)

**Comment by nuynait** [comment]
in addition https://github.com/jason0x43/jc-toggl 
I tried this tool which made by you as well and I have no problem input the api key in that workflow.

**Comment by jason0x43** [comment]
Release 1.1.3 had a rather glaring bug in how UI scripting responses were parsed. 1.1.4 is out now and should take care of that. Please give it another try. :)

**Comment by nuynait** [comment]
It works. Thanks
