### ISSUE TITLE
Timer action does not resume entries, only adds new ones

### ISSUE THREAD

**Issue by rockymountainhigh1943** [jason0x43/alfred-toggl#8]
I have my Toggl settings configured (and personal workflow) so that I resume each entry, rather than logging a new entry each time. Is this only available to add new entries?

**Comment by jason0x43** [comment]
Interesting, I've never used that functionality before, but I see what they're doing. It's actually handled at the client level (setting the option on Toggl's site only changes how the Toggl web app talks to the API), so I'll need to add an option to the workflow. Totally doable, though.

**Comment by rockymountainhigh1943** [comment]
That would be AMAZING if you could get this working with that
alternative tracking method!! I know for sure there would be tons of
folks that would use this if that option was available. When I first
showed this to my colleagues that use Toggl+Alfred -- that was the only
shortcoming. I was still very impressed but was sad I couldn't
immediately integrate this into my everyday workflow. 

Thanks for the really great work on this! 

Take care,
Jake

**Comment by jason0x43** [comment]
This feature was added in e47535d2b09044e4add28db48e97655d5afe709f, and is in release 1.1.5

**Comment by rockymountainhigh1943** [comment]
I noticed this was marked fixed in 1.1.5 -- but I'm still noticing the same behavior of only starting new entries -- not continuing. I use the desktop app while using this workflow and that is where you can see this behavior. Perhaps this is only meant for the web app?

Thanks so much for all your work on this awesome workflow. It's almost perfect for what I need!

**Comment by jason0x43** [comment]
The option to create new time entries or extend existing ones is currently client-specific, so if you enable it in the Alfred workflow, the workflow will extend entries but the web and desktop clients will keep their existing behavior. If you turn it on in the web interface, the web client (and maybe the desktop one) will extend entries, but the Alfred workflow will keep its existing behavior.
