### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by bvanpeski** [jason0x43/alfred-toggl#9]
Not an actual issue, just grateful to have found this. I just started experimenting with Toggl and was hoping to reduce some friction in tracking items by using Alfred instead. Stoked that someone already solved the issue!

![excellent](https://cloud.githubusercontent.com/assets/4316081/6958268/314b3346-d8be-11e4-94ee-91cea2dd2a00.gif)

**Comment by jason0x43** [comment]
:)
